name: "build"

on: [pull_request, push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: create files
        run: |
          mkdir build
          echo Test >> build/file

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifacts
          path: build/*
